daily coding practice 6 is added
waghmaresuyog/NewMyWayRepo pull request #12
Opened 2023-05-29 05:53 UTC by waghmaresuyog

2023-05-30 07:46 UTC, deepakghadge19 requested changes

2023-05-30 07:46 UTC, deepakghadge19 commented on simple/src/codingPractice/ShapeOfTraingle.java
> +
Format the code

2023-05-30 08:21 UTC, waghmaresuyog commented on simple/src/codingPractice/ShapeOfTraingle.java
> +
Done

2023-05-30 10:16 UTC, deepakghadge19 approved these changes

2023-06-02 08:13 UTC, Vrushalee1234 approved these changes

2023-06-02 08:22 UTC, merged