Coding practice15
waghmaresuyog/NewMyWayRepo pull request #21
Opened 2023-06-12 05:48 UTC by waghmaresuyog

2023-06-12 07:21 UTC, Ams12 requested changes

2023-06-12 07:21 UTC, Ams12 commented on simple/src/overridingExample/MainSport.java
> +
Remove the extra space.

2023-06-12 07:21 UTC, Ams12 commented on simple/src/overridingExample/Sport.java
> +
Same here.

2023-06-13 10:10 UTC, waghmaresuyog commented on simple/src/overridingExample/Sport.java
> +
Done

2023-06-16 09:50 UTC, amitsahu8 approved these changes

2023-06-16 09:50 UTC, merged