Coding practice 16 added
waghmaresuyog/NewMyWayRepo pull request #22
Opened 2023-06-13 06:31 UTC by waghmaresuyog

2023-06-13 06:38 UTC, amitsahu8 requested changes

2023-06-13 06:38 UTC, amitsahu8 commented on simple/src/codingPractice/MergeTwoList.java
> +        for (int index = 0; index < maxLength; index++) {
Sort the merged list

2023-06-13 08:43 UTC, waghmaresuyog commented on simple/src/codingPractice/MergeTwoList.java
> +        for (int index = 0; index < maxLength; index++) {
Done

2023-06-19 10:29 UTC, amitsahu8 approved these changes

2023-06-19 10:29 UTC, merged