Coding practice 19
waghmaresuyog/NewMyWayRepo pull request #25
Opened 2023-06-16 08:40 UTC by waghmaresuyog

2023-06-16 09:01 UTC, Ams12 requested changes

2023-06-16 09:01 UTC, Ams12 commented on simple/src/codingPractice/ReverseWords.java
> +    public static String reverseWords(String sentence) {
Give space between class and method.

2023-06-21 05:34 UTC, waghmaresuyog commented on simple/src/codingPractice/ReverseWords.java
> +
done

2023-06-21 05:34 UTC, waghmaresuyog commented on simple/src/codingPractice/ReverseWords.java
> +    public static String reverseWords(String sentence) {
done

2023-06-28 06:32 UTC, prashantkawa approved these changes

2023-06-29 06:34 UTC, anushreeSonak approved these changes
Approving PR

2023-06-29 06:34 UTC, merged