Coding Practice 21
waghmaresuyog/NewMyWayRepo pull request #27
Opened 2023-06-21 06:37 UTC by waghmaresuyog

2023-06-21 09:51 UTC, anushreeSonak commented on simple/src/codingPractice/StreamString.java
> +    public static void main(String[] args) {
please give space here

2023-06-21 09:51 UTC, anushreeSonak commented on simple/src/codingPractice/StreamString
> +Process finished with exit code 0
give proper name to READme file

2023-06-28 06:23 UTC, waghmaresuyog commented on simple/src/codingPractice/StreamString.java
> +    public static void main(String[] args) {
done

2023-06-28 06:27 UTC, waghmaresuyog commented on simple/src/codingPractice/StreamString
> +Process finished with exit code 0
Done

2023-06-29 06:36 UTC, anushreeSonak approved these changes

2023-07-03 09:22 UTC, prashantkawa requested changes

2023-07-03 09:22 UTC, prashantkawa commented on simple/src/codingPractice/StreamString.java
> +        long length =color.stream().filter(sort ->sort.startsWith(String.valueOf(startingLetter))).count();
Variable name should be proper

2023-07-03 11:56 UTC, prashantkawa approved these changes

2023-07-03 11:56 UTC, merged