Coding Practice 22
waghmaresuyog/NewMyWayRepo pull request #28
Opened 2023-06-28 05:19 UTC by waghmaresuyog

2023-06-29 08:51 UTC, anushreeSonak commented on simple/src/codingPractice/Flight.java
> +
remove extra space

2023-06-29 08:56 UTC, anushreeSonak commented on simple/src/codingPractice/Main.java
> +
remove above extra spaces

2023-06-29 08:57 UTC, anushreeSonak commented on simple/src/codingPractice/Main.java
> +public class Main {
Class Name should be meaningful.

2023-06-30 07:34 UTC, anushreeSonak approved these changes

2023-07-03 09:28 UTC, prashantkawa requested changes

2023-07-03 09:28 UTC, prashantkawa commented on simple/src/codingPractice/TravelApp.java
> +    private ArrayList<Flight> flights;
add space here

2023-07-03 09:28 UTC, prashantkawa commented on simple/src/codingPractice/TravelApp.java
> +    public void cancelReservation(int confirmationNumber) {
Removing flight details or cancelling reservation here?

2023-07-03 11:25 UTC, waghmaresuyog commented on simple/src/codingPractice/TravelApp.java
> +    private ArrayList<Flight> flights;
Done

2023-07-03 11:25 UTC, waghmaresuyog commented on simple/src/codingPractice/TravelApp.java
> +    public void cancelReservation(int confirmationNumber) {
Removing flight details

2023-07-03 11:26 UTC, waghmaresuyog commented on simple/src/codingPractice/Main.java
> +public class Main {
done

2023-07-03 11:26 UTC, waghmaresuyog commented on simple/src/codingPractice/Main.java
> +
done

2023-07-03 11:26 UTC, waghmaresuyog commented on simple/src/codingPractice/Flight.java
> +
done

2023-07-03 11:59 UTC, prashantkawa approved these changes

2023-07-03 11:59 UTC, merged