Coding practice 24
waghmaresuyog/NewMyWayRepo pull request #30
Opened 2023-07-06 07:04 UTC by waghmaresuyog

2023-07-06 11:11 UTC, anushreeSonak approved these changes

2023-07-07 05:58 UTC, prashantkawa requested changes

2023-07-07 05:58 UTC, prashantkawa commented on simple/src/codingPractice/SpecificWord.java
> +}
Try writing logic in separate method

2023-07-07 05:58 UTC, prashantkawa commented on simple/src/codingPractice/SpecificWord.java
> +        boolean flagOne = colors.stream().anyMatch(containWordOne);
repeating same steps again and again

2023-07-07 11:03 UTC, waghmaresuyog commented on simple/src/codingPractice/SpecificWord.java
> +}
Done

2023-07-07 11:03 UTC, waghmaresuyog commented on simple/src/codingPractice/SpecificWord.java
> +        boolean flagOne = colors.stream().anyMatch(containWordOne);
Done

2023-07-07 12:25 UTC, prashantkawa approved these changes

2023-07-07 12:25 UTC, merged